library(readr)
library(magrittr)
library(plotly)

# The data appear to be generated by a hyperbolic paraboloid function. My best
# approximation of the function is C = 10 - 0.4 * A^2 * B + 2 * A - 3 * B. One
# extreme outlier (row 201) was found and removed.

data <- readr::read_csv('./adops_data_regression.csv', 
                        col_names = c("A", "B", "C"))

# 3d plot of datapoints
library(plotly)
plot_ly(data[-201,], x = ~A, y = ~B, z = ~C, marker=list(color='blue', size=2)) %>%
  add_markers()

# Model and summary
m <- lm(C ~ I(A^2*B) + A + B, data = data[-201,])
summary(m)

# Diagnostic plots of residuals
par(mfrow = c(2,2))
plot(m)

# Note that while residuals are small, they do not appear to be normal /
# independent. Additional small refinements to the model could likely be made,
# time permitting.
